### ISSUE TITLE
Please help with FATAL: Lisp-Engine memory init: Data size mismatch error, cannot continue.

### ISSUE THREAD

**Issue by Poikilos** [pgrawehr/golgotha#1]
I [fixed several issues](https://github.com/poikilos/golgotha/issues?q=is%3Aissue+is%3Aclosed) in my fork, some of which are Linux-specific. However, after all that, I still get `FATAL: Lisp-Engine memory init: Data size mismatch error, cannot continue.` (I found the error and exit calls in `lisp__lisp.cpp`). See [issue 13 on my fork](https://github.com/poikilos/golgotha/issues/13) for details. I am having trouble understanding why the problem occurs or how to fix it.

**Comment by pgrawehr** [comment]
@poikilos Sorry for not seeing this. I haven't touched that in a while, but I'm sure it used to work under linux, too. I'll test when I find time.

**Comment by Poikilos** [comment]
> @poikilos Sorry for not seeing this. I haven't touched that in a while, but I'm sure it used to work under linux, too. I'll test when I find time. 

Do you think maybe it assumes 32-bit compilation when defining types? I thought of that recently and maybe it uses a type for character or byte that is bigger on 64bit or on the modern compiler(s).

**Comment by pgrawehr** [comment]
Oh, are you trying to build with 64 bit? That has never been attempted, and this could very well cause this problem. The lisp memory manager includes a garbage collector that is highly dependent on address and offset sizes. I'm sure you need to adjust some of the data structures there to get it to work in 64 bit mode.

**Comment by Poikilos** [comment]
Tried:
```
# export CFLAGS=-m32
# ^ has no effect
export CPPFLAGS=-m32
# ^ works (-m32 gets added to gcc commands)
./configure
make clean
make
```
but `make` says:
```
/usr/bin/ld: linux-gnu_release/video__x11__x11_input.o: undefined reference to symbol 'XSetForeground'
/usr/bin/ld: /lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
```

Can you offer any assistance?

Note that my other changes are still necessary so I suggest starting with my fork.

:edit: see other things I tried at the issue: https://github.com/poikilos/golgotha/issues/14

**Comment by pgrawehr** [comment]
I'll try to take a look. Unfortunately, I have a bunch of other open projects at this time. But I should be able to get to it this week.

**Comment by pgrawehr** [comment]
I took a look into building with 64 bit (on Windows), but this didn't get very far. The whole memory manager assumes a pointer size of 4 all over the place. It could probably just be removed and replaced with standard malloc/free, but that needs quite a bit of time, and I have some more urgent projects to do right now. 

I'm really no export for building on linux, particularly in a cross-build environment. If you need to get this to run on linux, I'd recommend you do some testing with a simple 32 bit test application first. I can try what you did, but I would have to google just like you did. 

The simplest start would be to run on Windows or in a 32 bit linux environment (maybe use a VM)

**Comment by Poikilos** [comment]
Thanks. It doesn't have that error when using 32-bit. The 32-bit opengl1 was not available on Devuan (chimaera) but is available on Fedora 35.
