### ISSUE TITLE
Function name errno cannot be used as variable name

### ISSUE THREAD

**Issue by Poikilos** [pgrawehr/golgotha#2]
Trying to compile in Visual Studio 2019 causes:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)	E0145	function "_errno" may not be initialized	ivcon	C:\Users\Owner\git\golgotha\ivcon\ivcon.cpp	63	
Error	MSB8041	MFC libraries are required for this project. Install them from the Visual Studio installer (Individual Components tab) for any toolsets and architectures being used.	Golgotha	C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets	479	
Error	C2059	syntax error: '='	ivcon	C:\Users\Owner\git\golgotha\ivcon\ivcon.cpp	63	
Error	RC1015	cannot open include file 'afxres.h'.	map2def	C:\Users\Owner\git\golgotha\map2def\map2def.rc	10	

```
![image](https://github.com/user-attachments/assets/9adf11ca-3707-4d19-8ac7-dd647c89436e)

@pgrawehr I have other issues at <https://github.com/Poikilos/golgotha/issues>. I understand that the game is not finished and development halted due to funds. I didn't post the issues here because I thought maintenance was also permanently halted, but then you made a commit after I forked it, though it is just a project file update for Windows. Please confirm whether maintenance is permanently halted or if you are able to help. If so I can post the issues here.

**Comment by pgrawehr** [comment]
I'm not doing any active development on it (due to time, mostly), but I try to at least make sure it keeps building with new compiler versions. And as such, I'm pretty sure it builds with VS2022 just fine. 

Did you install the MFC library as suggested by the second error message?

**Comment by Poikilos** [comment]
I will try to factor MFC out, as well as the conflicting variable name. I'm working on getting it to build on linux as well. I guess I'll have to do it. See my fork for several previous linux-related changes.
